package net.gregrapp.jhouse

import net.gregrapp.jhouse.events.*
import net.gregrapp.jhouse.events.TimeEvent.TimeEventType
import net.gregrapp.jhouse.states.*
import net.gregrapp.jhouse.device.*
import net.gregrapp.jhouse.device.classes.*
import net.gregrapp.jhouse.device.drivers.types.*

global net.gregrapp.jhouse.managers.device.DeviceManager dm
global net.gregrapp.jhouse.services.email.EmailService email

declare DeviceValueEvent
	@role( event )
	@timestamp( time )
end

declare DeviceTextEvent
	@role( event )
	@timestamp( time )
end

declare TimeEvent
	@role( event )
	@timestamp( time )
end

declare Device
	@propertyChangeSupport
end

declare DriverDevice
	@propertyChangeSupport
end
