package net.gregrapp.jhouse

import net.gregrapp.jhouse.events.*
import net.gregrapp.jhouse.events.TimeEvent.TimeEventType
import net.gregrapp.jhouse.device.*
import net.gregrapp.jhouse.device.classes.*
import net.gregrapp.jhouse.device.drivers.types.*

global net.gregrapp.jhouse.services.DeviceService device
global net.gregrapp.jhouse.services.EmailService email
global net.gregrapp.jhouse.services.AppleApnsService apns

declare DeviceValueEvent
	@role( event )
	@timestamp( time )
end

declare DeviceTextEvent
	@role( event )
	@timestamp( time )
end

declare TimeEvent
	@role( event )
	@timestamp( time )
end

declare Device
	@propertyChangeSupport
end

declare DriverDevice
	@propertyChangeSupport
end
