/*
rule "1"
	no-loop
	when
		$event : BinarySwitchStateEvent(id == 1, state == 255) 
		$device : ZwaveBinarySwitch(deviceId == 2)
	then
		System.out.println("********** GOT SWITCH ON EVENT FOR DEVICE 1");
		dm.execute(2, "setOff");
		modify ( $device )
		{
			setOff()
		}
	end

rule "2"
	when
		BinarySwitchStateEvent(deviceId == 1, state == 0)
	then
		System.out.println("********** GOT SWITCH OFF EVENT FOR DEVICE 1");
	end

rule "3"
	timer ( cron: 1 * * * * ? )
	when
	then
		//((MultilevelSwitch)dm.get(1)).setLevel(100);
		System.out.println("*********** TIMER3 EXPIRED");
	end

rule "4"
	timer ( cron: 10 * * * * ? )
	when
	then
		//((MultilevelSwitch)dm.get(1)).setLevel(25);
		System.out.println("*********** TIMER4 EXPIRED");
	end

rule "5"
	when
		Device(id == 15, value == 255)
	then
		System.out.println("************ NEW SWITCH ON EVENT FOR DEVICE 15");
	end

rule "6"
	when
		Device(id == 30, value == 255)
	then
		System.out.println("*********** MASTER BATHROOM DOOR OPEN");
	end

rule "7"
	when
		Device(id == 30, value == 0)
	then
		System.out.println("*********** MASTER BATHROOM DOOR CLOSED");
	end
*/

rule "8"
	when
		DeviceValueEvent(id == 15, value == 255, changed == true)
	then
		System.out.println("************ NEW SWITCH CHANGED ON EVENT FOR DEVICE 15");
		dm.get(23, DriverDevice.class).getDriver().setOn();
	end

rule "9"
	when
		DeviceValueEvent(id == 15, value == 0, changed == true)
	then
		System.out.println("************ NEW SWITCH CHANGED OFF EVENT FOR DEVICE 15");	
		dm.get(23).getDriver().setOff();
	end

rule "10"
	when
		DeviceValueEvent(id == 15, value == 255, changed == false)
	then
		System.out.println("************ NEW SWITCH SET ON EVENT FOR DEVICE 15");	
	end
	
