import net.gregrapp.jhouse.events.*
import net.gregrapp.jhouse.states.*
import net.gregrapp.jhouse.device.types.*
import net.gregrapp.jhouse.device.drivers.*

declare BinarySwitchStateEvent
	@role( event )
	@timestamp ( time )
end

rule "1"
	when
		BinarySwitchStateEvent(deviceId == 1, state == BinarySwitchState.ON) 
		$device : ZwaveBinarySwitch(deviceId == 2)
	then
		System.out.println("********** GOT SWITCH ON EVENT FOR DEVICE 1");
		modify ( $device )
		{
			setOff()
		}
	end

rule "2"
	when
		BinarySwitchStateEvent(deviceId == 1, state == BinarySwitchState.OFF)
	then
		System.out.println("********** GOT SWITCH OFF EVENT FOR DEVICE 1");
	end

rule "3"
	timer ( cron: 0 * * * * ? )
	when
	
	then
		System.out.println("*********** TIMER EXPIRED");
	end
	